const defaultData={homeTitle:'Luxury Villas, Land & Investment Projects',homeIntro:'Rüya Global Estate offers carefully selected villas, sea-view land and project-based investment opportunities for international buyers.',heroImage:'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',aboutTitle:'Trusted Real Estate Guidance',aboutText:'Welcome to Rüya Global Estate. We help buyers find secure, beautiful and high-value property opportunities in Türkiye with clear communication and professional service.',aboutPhoto:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',signature:'Emma Karademir • Sales Manager',listings:{villas:[{title:'Kocaali Yalı 4+1 Luxury Villa',price:'10,500,000 TL',image:'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=900&q=80',desc:'Detached entrance, garden, pool, underfloor heating, master bathroom and premium stone details.'}],land:[{title:'Investment Land in Sakarya',price:'Contact for price',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80',desc:'Suitable plots for villa and project-based development opportunities.'}],projects:[{title:'Project-Based Sales Opportunities',price:'Pre-sale options',image:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80',desc:'Selected construction and investment projects for international buyers.'}]}}};
let data=JSON.parse(localStorage.getItem('ruya_site_data')||'null')||defaultData;
document.getElementById('year').textContent=new Date().getFullYear();
function save(){localStorage.setItem('ruya_site_data',JSON.stringify(data));}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));[...document.querySelectorAll('.nav button')].find(b=>b.textContent.toLowerCase().startsWith(id==='villas'?'villas':id))?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function listingHTML(item,type,i){return `<article class="listing card"><img src="${item.image}" alt="${item.title}"><h3>${item.title}</h3><div class="price">${item.price}</div><p>${item.desc}</p><a class="goldBtn" href="https://wa.me/905342871106?text=${encodeURIComponent('I am interested in '+item.title)}">Ask on WhatsApp</a><button class="deleteBtn adminOnly hidden" onclick="deleteListing('${type}',${i})">Delete</button></article>`}
function render(){homeTitle.textContent=data.homeTitle;homeIntro.textContent=data.homeIntro;heroImage.src=data.heroImage;aboutTitle.textContent=data.aboutTitle;aboutText.textContent=data.aboutText;aboutPhoto.src=data.aboutPhoto;signature.textContent=data.signature;['villas','land','projects'].forEach(t=>document.getElementById(t+'List').innerHTML=data.listings[t].map((x,i)=>listingHTML(x,t,i)).join(''));}
render();
function openAdmin(){adminModal.classList.add('show')}function closeAdmin(){adminModal.classList.remove('show')}
function loginAdmin(){if(adminPass.value==='ruya2026'){loginBox.classList.add('hidden');adminPanel.classList.remove('hidden');document.querySelectorAll('.adminOnly').forEach(e=>e.classList.remove('hidden'));fillAdmin();}else alert('Wrong password')}
function fillAdmin(){gaInput.value=localStorage.getItem('ruya_ga_id')||'';editHomeTitle.value=data.homeTitle;editHomeIntro.value=data.homeIntro;editHeroImage.value=data.heroImage;editAboutTitle.value=data.aboutTitle;editAboutText.value=data.aboutText;editAboutPhoto.value=data.aboutPhoto;editSignature.value=data.signature;}
function saveContent(){data.homeTitle=editHomeTitle.value;data.homeIntro=editHomeIntro.value;data.heroImage=editHeroImage.value;data.aboutTitle=editAboutTitle.value;data.aboutText=editAboutText.value;data.aboutPhoto=editAboutPhoto.value;data.signature=editSignature.value;if(gaInput.value){localStorage.setItem('ruya_ga_id',gaInput.value.trim());}save();render();alert('Saved on this device. Reload for Analytics if GA ID changed.');}
function addListing(){let t=newType.value;if(!newTitle.value)return alert('Title required');data.listings[t].push({title:newTitle.value,price:newPrice.value,image:newImage.value||'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',desc:newDesc.value});save();render();newTitle.value=newPrice.value=newImage.value=newDesc.value='';alert('Listing added');}
function deleteListing(t,i){if(confirm('Delete this listing?')){data.listings[t].splice(i,1);save();render();document.querySelectorAll('.adminOnly').forEach(e=>e.classList.remove('hidden'));}}
function exportBackup(){importData.value=JSON.stringify(data,null,2);navigator.clipboard?.writeText(importData.value);alert('Backup copied.');}
function importBackup(){try{data=JSON.parse(importData.value);save();render();alert('Imported');}catch(e){alert('Backup text is invalid');}}
